"""Generate a Python module containing the Flask/Jinja templates for Workers.

Cloudflare Python Workers bundle Python modules, while Flask normally loads
Jinja templates from the filesystem.  This build step makes the existing
``templates/`` directory available to Flask through ``DictLoader`` without
requiring any template rewrites.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = ROOT / "templates"
OUTPUT = ROOT / "template_bundle.py"


def main() -> None:
    templates = {}
    for path in sorted(TEMPLATE_DIR.rglob("*")):
        if path.is_file():
            key = path.relative_to(TEMPLATE_DIR).as_posix()
            templates[key] = path.read_text(encoding="utf-8")

    lines = [
        '"""Generated by tools/bundle_templates.py. Do not edit by hand."""',
        "",
        "TEMPLATES = {",
    ]
    for name, source in templates.items():
        lines.append(f"    {name!r}: {source!r},")
    lines.append("}")
    lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Bundled {len(templates)} templates -> {OUTPUT.name}")


if __name__ == "__main__":
    main()
